Write a NumPy program to get the numpy version and show numpy build configuration

In [0]:
import pandas as pd
import numpy as np

Write a NumPy program to create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal

In [2]:
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


Write a NumPy program to create a 3x3x3 array filled with arbitrary values

In [3]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.93380157 0.99511231 0.44661874]
  [0.17768482 0.9152183  0.27564003]
  [0.68457106 0.15264474 0.09443995]]

 [[0.28954619 0.0490385  0.97537943]
  [0.34927664 0.36416981 0.98320656]
  [0.84737072 0.07728036 0.4753952 ]]

 [[0.67566018 0.34046116 0.32752936]
  [0.09251259 0.32094122 0.56712811]
  [0.94792253 0.77790125 0.27051734]]]


Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of an given array.

In [4]:
x = np.array([[0,1],[2,3]])
print(x)
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[0 1]
 [2 3]]
6
[2 4]
[1 5]


 Write a NumPy program to compute the inner product of two given vectors

In [5]:
x = np.array([42, 52])
y = np.array([17, 20])
print(x)
print(y)
print(np.dot(x, y))

[42 52]
[17 20]
1754


Write a NumPy program to add a vector to each row of a given matrix

In [6]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
print(v)
print(m)
result = np.empty_like(m) 
for i in range(4):
  result[i, :] = m[i, :] + v
print(result)

[1 1 0]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


Write a NumPy program to save a given array to a binary file

In [8]:
import os
a = np.arange(20)
np.save('temparra.npy', a)
if os.path.exists('temparra.npy'):
    x2 = np.load('temparra.npy')
    print(np.array_equal(a, x2))

True


Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it

In [9]:
import os
x = np.arange(10)
y = np.arange(11, 20)
print(x)
print(y)
np.savez('temparra.npz', x=x, y=y)
with np.load('temparra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


Write a NumPy program to save a given array to a text file and load it

In [10]:
import os
x = np.arange(12).reshape(4, 3)
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
result = np.loadtxt('temp.txt')
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
