Write a NumPy program to get the numpy version and show numpy build configuration

In [0]:
import pandas as pd
import numpy as np

Write a NumPy program to create a 3X4 array using and iterate over it.

In [2]:
a = np.arange(10,22)
a.reshape((3, 4))
for x in np.nditer(a):
  print(x,end=" ")

10 11 12 13 14 15 16 17 18 19 20 21 

Write a NumPy program to create a vector of length 10 with values ​​evenly distributed between 5 and 50.

In [3]:
v = np.linspace(10, 49, 5)
v

array([10.  , 19.75, 29.5 , 39.25, 49.  ])

Write a NumPy program to create a vector with values ​​from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [4]:
x = np.arange(20)
print(x)
x[(x >= 9) & (x <= 15)] *= -1
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [5]:
x = np.random.randint(0, 11, 5)
print(x)

[ 1 10  9  1  1]


Write a NumPy program to multiply the values of two given vectors

In [6]:
x = np.array([1, 8, 3, 5])
print(x)
y= np.random.randint(0, 11, 4)
print(y)
result = x * y
print(result)

[1 8 3 5]
[1 1 3 6]
[ 1  8  9 30]


Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [7]:
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


Write a NumPy program to find the number of rows and columns of a given matrix

In [8]:
m= np.arange(10,22).reshape((3, 4))
print(m)
print(m.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
(3, 4)


Write a NumPy program to create a 4x4 identity matrix, i.e. diagonal elements are 1, the rest are 0

In [11]:
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [12]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

In [13]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
