Write a NumPy program to get the numpy version and show numpy build configuration

In [0]:
import pandas as pd
import numpy as np

Write a NumPy program to compute the multiplication of two given matrixes

In [2]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
result = np.dot(p, q)
print(result)

[[1 2]
 [3 4]]


Write a NumPy program to compute the outer product of two given vectors.

In [0]:
result = np.outer(p, q)

Write a NumPy program to compute the cross product of two given vectors

In [4]:
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print(result1)
print("")
print(result2)

[ 2 -3]

[-2  3]


Write a NumPy program to compute the determinant of a given square array.

In [5]:
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))

Original 2-d array
[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension

In [6]:
a = np.array([1,2,5])
b = np.array([2,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
print 
result = np.inner(a, b)
print("Inner product of the said vectors:")
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Higher dimension arrays:")
print(x)
print(y)
result = np.inner(x, y)
print("Inner product of the said vectors:")
print(result)

Original 1-d arrays:
[1 2 5]
[2 1 0]
Inner product of the said vectors:
Higher dimension arrays:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Inner product of the said vectors:
[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square arra

In [7]:
m = np.mat("3 -2;1 0")
print("Original matrix:")
print("a\n", m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix",v)

Original matrix:
a
 [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


Write a NumPy program to compute the condition number of a given matrix.

In [8]:
from numpy import linalg as LA
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print("Original matrix:")
print(a)
print("The condition number of the said matrix:")
print(LA.cond(a))

Original matrix:
[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
The condition number of the said matrix:
1.4142135623730951


Write a NumPy program to find a matrix or vector norm

In [9]:
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)

Vector norm:
9.539392014169456
Matrix norm:
5.477225575051661


Write a NumPy program to compute the determinant of an array.

In [10]:
a = np.array([[1,2],[3,4]])
print("Original array:")
print(a)
result =  np.linalg.det(a)
print("Determinant of the said array:")
print(result)

Original array:
[[1 2]
 [3 4]]
Determinant of the said array:
-2.0000000000000004


Write a NumPy program compute the inverse of a given matrix

In [11]:
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]
