In [0]:
import numpy as np

In [14]:
lst = [1,2,3]
array = np.array(lst)
print(array)

[1 2 3]


In [15]:
lst2 = [[1,2,3],[4,5,6],[7,8,9]]
array2 = np.array(lst2, float)
print(array2)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [16]:
type(lst2)

list

In [17]:
lst[1:]

[2, 3]

In [18]:
print(array2[0, 1:])

[2. 3.]


In [19]:
print(array2[1, 2])

6.0


In [20]:
array.shape

(3,)

In [21]:
axis = list(array.shape)
axis[0]

3

In [22]:
np.mean(array2)

5.0

In [23]:
np.mean(array)

2.0

In [0]:
a = np.dot(array, array2)

In [26]:
a.shape

(3,)

In [27]:
# coefficient matrix 
A = np.array([[1, 2, -1], [2, 1, 1], [1, 2, 1]])

# numbers on the right without variables
b = np.array([4, -2, 2])

# solve using np.linagl.solve()
np.linalg.solve(A, b)

array([-1.66666667,  2.33333333, -1.        ])