Write a NumPy program to get the numpy version and show numpy build configuration

In [0]:
import pandas as pd
import numpy as np

In [2]:
print(np.__version__)
print(np.show_config())

1.17.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


Write a NumPy program to test whether none of the elements of a given array is zero.

In [3]:
x = np.array([1, 2, 3, 4])
print("array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("array is zero:")
print(np.all(x))

array is zero:
True
array is zero:
False


Write a NumPy program to test if any of the elements of a given array is non-zero.

In [4]:
print(np.any(x))

True


Write a NumPy program to test element-wise for NaN of a given array.

In [5]:
a = np.array([ np.nan, 22, np.nan, np.inf])
print("Test element-wise for NaN:")
print(np.isnan(a))

Original array
[nan 22. nan inf]
Test element-wise for NaN:
[ True False  True False]


Write a NumPy program to create a 3x3 identity matrix

In [6]:
array=np.identity(3)
print('3x3 matrix:')
print(array)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Write a NumPy program to create an array of all the even integers from 200 to 850

In [7]:
array=np.arange(200,850,24)
print("Array of all the even integers from 200 to 850")
print(array) 

Array of all the even integers from 30 to 70
[200 224 248 272 296 320 344 368 392 416 440 464 488 512 536 560 584 608
 632 656 680 704 728 752 776 800 824 848]


Write a NumPy program to create an array of all the even integers from 30 to 70.

In [8]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
rand_num = np.random.normal(0,1,2)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[-0.78744324 -0.59493324]


Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.

In [11]:
vektor = np.arange(15,55)
print(vektor[1:15])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29]
