Write a NumPy program to get the numpy version and show numpy build configuration

In [0]:
import pandas as pd
import numpy as np

Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [2]:
l = [12.23, 13.32, 100, 36.32]
a = np.array(l)
a

array([ 12.23,  13.32, 100.  ,  36.32])

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
x =  np.arange(2, 11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [4]:
x = np.zeros(10)
print(x)
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


Write a NumPy program to create a array with values ranging from 12 to 38

In [5]:
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


Write a NumPy program to reverse an array (first element becomes last)

In [6]:
x = np.arange(12, 38)
print(x)
x = x[::-1]
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


Write a NumPy program to an array converted to a float type

In [7]:
a = [1, 2, 3, 4]
print(a)
x = np.asfarray(a)
print(x)

[1, 2, 3, 4]
[1. 2. 3. 4.]


Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [9]:
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print()
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Write a NumPy program to add a border (filled with 0's) around an existing array

In [10]:
x = np.ones((3,3))
print(x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
