In [0]:
import pandas as pd
import numpy as np

Write a Python program to find the maximum and minimum value of a given flattened array.

In [2]:
a = np.arange(4).reshape((2,2))
print(a)
print(np.amax(a))
print(np.amin(a))

[[0 1]
 [2 3]]
3
0


Write a NumPy program to get the minimum and maximum value of a given array along the second axis

In [3]:
x = np.arange(4).reshape((2, 2))
print(x)
print(np.amax(x, 1))
print(np.amin(x, 1))

[[0 1]
 [2 3]]
[1 3]
[0 2]


Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.

In [4]:
x = np.arange(12).reshape((2, 6))
print(x)
r1 = np.ptp(x, 1)
r2 = np.amax(x, 1) - np.amin(x, 1)
assert np.allclose(r1, r2)
print(r1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[5 5]


Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis

In [5]:
x = np.arange(18).reshape((3, 6))
print(x)
r1 = np.percentile(x, 80, 1)
print(r1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[ 4. 10. 16.]


Write a NumPy program to compute the weighted of a given array

In [7]:
x = np.arange(5)
print("\nOriginal array:")
print(x)
weights = np.arange(1, 6)
r1 = np.average(x, weights=weights)
r2 = (x*(weights/weights.sum())).sum()
assert np.allclose(r1, r2)
print("\nWeighted average of the said array:")
print(r1)


Original array:
[0 1 2 3 4]

Weighted average of the said array:
2.6666666666666665


Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis.

In [8]:
x = np.arange(6)
print("\nOriginal array:")
print(x)
r1 = np.mean(x)
r2 = np.average(x)
assert np.allclose(r1, r2)
print("\nMean: ", r1)
r1 = np.std(x)
r2 = np.sqrt(np.mean((x - np.mean(x)) ** 2 ))
assert np.allclose(r1, r2)
print("\nstd: ", 1)
r1= np.var(x)
r2 = np.mean((x - np.mean(x)) ** 2 )
assert np.allclose(r1, r2)
print("\nvariance: ", r1)


Original array:
[0 1 2 3 4 5]

Mean:  2.5

std:  1

variance:  2.9166666666666665


Write a NumPy program to compute the covariance matrix of two given arrays.

In [9]:
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]
