In [0]:
import numpy as np

In [2]:
#buatlah numpy array random dengan nilai 6-20
array = np.arange(6,21)
print(array)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
#buatlah matriks 2D denga ukuran 3x3
array = np.arange(1,10).reshape(3,3) 
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#covert list ini menjadi array 1 dimensi
#List: [12.23, 13.32, 100, 36.32]
array = np.array([12.23, 13.32, 100, 36.32],float)
print(array)

[ 12.23  13.32 100.    36.32]


In [5]:
#buatlah vektor 0 dengan ukuran 10 dan update nilai ke 8 dengan nilai 10
array = np.zeros(12)
array[8] = 10
print(array)

[ 0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.  0.]


In [6]:
#buatlah array lalu reverse array tersebut
array = np.array([12.23, 13.32, 100, 36.32,10,93,10], int)
array[::-1]

array([ 10,  93,  10,  36, 100,  13,  12])

In [7]:
array = np.ones((5,5))
array[1:4,1:4] = 8
print(array)

[[1. 1. 1. 1. 1.]
 [1. 8. 8. 8. 1.]
 [1. 8. 8. 8. 1.]
 [1. 8. 8. 8. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
#perkalian dua matriks
a = [[1, 1], 
     [0, 1]]

b = [[1, 2], 
     [3, 4]]

c = np.dot(a,b)

c

array([[4, 6],
       [3, 4]])

In [9]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("cross product of the said two vectors(p, q):")
print(result1)
print("cross product of the said two vectors(q, p):")
print(result2)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
cross product of the said two vectors(p, q):
[ 2 -3]
cross product of the said two vectors(q, p):
[-2  3]
