NumPy Exercise - Aji Rahmat

In [2]:
import numpy as np
import pandas as pd
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#array two dimension
b = np.array([['Name','Aji Rahmat'],['Birth Date','11-August-1997'],['University', 'Telkom University']])
print(b)

[['Name' 'Aji Rahmat']
 ['Birth Date' '11-August-1997']
 ['University' 'Telkom University']]


In [9]:
c = np.array(['a','b','c'], ndmin=2)
print(c)

[['a' 'b' 'c']]


In [11]:
d = np.array([2,3,4,5], dtype=complex)
print(d)

[2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [12]:
dt = np.dtype(np.int32) 
print(dt)

int32


In [29]:
#shape to know array size 
x = np.array([[1,2,3],['a','b,','c']])
print(x.shape)

(2, 3)


In [26]:
# this resizes the ndarray 
z = np.array([[1,2,3],[4,5,6]]) 
z.shape = (3,2)
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
#resahpe array
w = z.reshape(2,3) 
print(w)

[[1 2 3]
 [4 5 6]]


In [34]:
q = np.arange(24) 
print(q)
print(q.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [37]:
e = np.arange(24) 
e.ndim  

# reshape
r = e.reshape(2,4,3) 
print(r)
# r isthree dimensions

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
