Write a NumPy program to get the numpy version and show numpy build configuration

In [0]:
import pandas as pd
import numpy as np

Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern

In [11]:
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Write a NumPy program to convert a list and tuple into arrays

In [12]:
alist = [1, 2, 3, 4, 5, 6, 7, 8]
print(np.asarray(alist))
atuple = ([8, 4, 6], [1, 2, 3])
print(np.asarray(atuple))

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


 Write a NumPy program to append values to the end of an array

In [13]:
x = [10, 20, 30]
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print(x)

[10, 20, 30]
[10 20 30 40 50 60 70 80 90]


 Write a NumPy program to create an empty and a full array

In [14]:
x = np.empty((2,3))
print(x)
y = np.full((3,3),6)
print(y)

[[1.98e-322 2.47e-322 2.96e-322]
 [3.46e-322 3.95e-322 4.45e-322]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


 Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

In [15]:
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print(F)
print(5*F/9 - 5*32/9)

[ 0.   12.   45.21 34.   99.91]
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

In [16]:
x = np.array([1,2,3], dtype=np.float64)
print("Size ", x.size)
print("Length ", x.itemsize)
print("Total bytes ", x.nbytes)

Size  3
Length  8
Total bytes  24


Write a NumPy program to find common values between two arrays

In [17]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
[10 40]


Write a NumPy program to get the unique elements of an array.

In [18]:
x = np.array([10, 10, 20, 20, 30, 30])
print(x)
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print(x)
print(np.unique(x))

[10 10 20 20 30 30]
[10 20 30]
[[1 1]
 [2 3]]
[1 2 3]


Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [19]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print(np.setdiff1d(array1, array2))


Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
[ 0 20 60 80]


Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

In [20]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]
